name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_LOGIN: shuu01
  DOCKER_IMAGE: webcalc 
  DOCKER_PASS: password1 

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Login to docker.io
      run:  echo ${DOCKER_PASS} | docker login -u ${DOCKER_LOGIN} --password-stdin
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_LOGIN/$DOCKER_IMAGE:${GITHUB_REF##*/}
    - name: Push image to dockerhub
      run: docker push  $DOCKER_LOGIN/$DOCKER_IMAGE:${GITHUB_REF##*/}

  
