name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_LOGIN: shuu01
  DOCKER_IMAGE: webcalc 
  DOCKER_PASS: password1 

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Login to docker.io
      run:  echo $DOCKER_PASS | docker login -u $DOCKER_LOGIN --password-stdin
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_LOGIN/$DOCKER_IMAGE:${GITHUB_REF##*/}
    - name: docker tag
      run: docker tag $DOCKER_LOGIN/$DOCKER_IMAGE:${GITHUB_REF##*/} $DOCKER_LOGIN/$DOCKER_IMAGE:latest
    - name: Push image to dockerhub
      run: docker push  $DOCKER_LOGIN/$DOCKER_IMAGE:${GITHUB_REF##*/}
    - name: push latest
      run: docker push $DOCKER_LOGIN/$DOCKER_IMAGE:latest

  test:
    
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: docker run
        run: docker run $DOCKER_LOGIN/$DOCKER_IMAGE -p 127.0.0.1:8000:8000 -d
      - name: test
        run: curl -s -X POST "http://127.0.0.1:8000/sum" -H  "accept: application/json" -H  "Content-Type: application/json" -d '{"a":1,"b":2}'
